protocol = "my-daemon"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://gitlab.com/yaq/yaqd-mqtt"
bugtracker = "https://gitlab.com/yaq/yaqd-mqtt/-/issues"

[installation]
PyPI = "https://pypi.org/project/yaqd-mqtt"

[config]

[state]

[messages]

